apiVersion: v1
kind: ConfigMap
metadata:
  name: vdlg-video-config
  namespace: vdlg
data:
  ENV: "dev"
  PORT: "8080"
  POSTGRES_DB: "vdlg_db"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "adminvdlg"
  POSTGRES_HOST: "vdlg-postgres-db.cdnilrkxgmpa.us-east-1.rds.amazonaws.com"
  INPUT_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/000047597454/ApiInputQueue" 
  OUTPUT_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/000047597454/ApiOutputQueue"
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "testetremzao"
