apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: tremligeiro
  labels:
    app: postgres
type: Opaque
data:
    POSTGRES_PASS: YWRtaW50cmVtbGlnZWlybw==
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: tremligeiro
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/minikube/directory/structure/"
    type: DirectoryOrCreate
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: tremligeiro
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
